### ISSUE TITLE
puka.html claims support for immediate arg, but code doesn't support it

### ISSUE THREAD

**Issue by vitaly-krugl** [majek/puka#61]
FYI:

Per http://majek.github.io/puka/puka.html: `Client.basic_publish(exchange, routing_key, mandatory=False, immediate=False, headers={}, body="")`.

But the code in https://github.com/majek/puka/blob/master/puka/machine.py doesn't have support for  `immediate`: `def basic_publish(conn, exchange, routing_key='', mandatory=False,  headers={}, body='')`

**Comment by majek** [comment]
https://github.com/majek/puka/commit/b5699c4ffdeeb1264a0a8a99b4221e945cc71057

Rabbitmq 3.0 doesn't do it I guess?

**Comment by vitaly-krugl** [comment]
Right, I meant that puka.html is out of sync.
