### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by majek** [majek/puka#7]
Python 3 should be supported.

**Comment by mwalkowski** [comment]
Hi, What is the status of?

**Comment by shayneoneill** [comment]
bump

**Comment by justinfx** [comment]
Any plans to maintain this project for python3? We use a locally patched version of 0.0.7 with py2.7 and it would be good to know the future of this project. Thanks!

**Comment by majek** [comment]
Do you have a PR?

**Comment by justinfx** [comment]
I think I worded that poorly. We use 0.0.7 with patches to the socket handling to fix bugs that we haven't yet contributed back to this upstream. But we don't have py3 support. I'm at the crossroads of deciding whether to investigate py3 support in Puka, or switch entirely to amqp 2.5.0. Keeping Puka has the benefit that we have already been using it in production for 6+ years and have fixed known edge cases at our studio. amqp has the benefit of being a single maintained dep with support for both, but we would then have to review if it covers our edge cases again.

**Comment by Br3nda** [comment]
@justinfx kiaora. The puka library is small. You could spend the time to upgrade to python 3. It would be an excellent way to contribute back for all the years of benefit had from open source.

**Comment by justinfx** [comment]
@Br3nda, I was considering doing the py3 patch and contributing it, but a handful of the unittests were failing out of the box on our RabbitMQ 3.6.6 cluster. I would want to have passing tests before I attempted an update, and I have been working to try and fix tests and also get it to clean up after itself. I think tests were failing for a while, even when we did local patches to Puka, but we have not been running the Puka tests, and instead validate our changes through our higher level library. 
But I wanted to check if there were any existing plans to port, which it seems there are not. Maybe @majek could confirm that the tests all pass on some semi-recent Rabbit version? I definitely wouldn't want to proceed with my own efforts to port unless they passed. 

Various failing tests:
* deleting queues and exchanges don't raise anymore if they don't exist
* basic_qos tests fail when they don't receive the next messages after the setting change

**Comment by Br3nda** [comment]
@justinfx is it on a public fork? Can have a look

**Comment by justinfx** [comment]
@Br3nda, our internal modifications aren't on a public fork, but they aren't actually relevant. What I meant was the master branch of this repo has tests that fail against our local rabbitmq 3.6.6 cluster. I ran against a clean checkout.

**Comment by justinfx** [comment]
I'm working on a py3 port now, just as an update. I've skipped the failing 2 qos tests and 2 delete test until I know why they don't work. 
Even if puka is a small library, its actually a lot more work than even some of my bigger projects, because it contains a lot of str vs byte handling situations. So far I have the rest of the tests passing with the changes under py2 and I am going to start working through py3. I can submit a PR once I have it passing.

**Comment by shayneoneill** [comment]
Hooray! Good work!
