### ISSUE TITLE
Release version 0.0.8 on pypi

### ISSUE THREAD

**Issue by NikolaiGulatz** [majek/puka#70]
The release on GitHub is already one month old, but the latest version on pypi is still 0.0.7

**Comment by mschreib28** [comment]
@majek just merged my PR with the update to the VERSION file. So once the new version is uploaded to PyPi then you should be able to reference it in your `requirements.txt` as `puka==0.0.8`

**Comment by mschreib28** [comment]
This has been updated on PyPi and can be closed.
